name: .NET Test

on:
  workflow_call:
    inputs:
      submodules:
        type: boolean
        default: false
        required: false
      checkout_token:
        required: false
        type: string

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      if: inputs.submodules == false
      
    - uses: actions/checkout@v3
      if: inputs.submodules == true
      with:
        submodules: true
        token: ${{ inputs.checkout_token }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
